# Generated by Django 3.1.2 on 2020-10-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(max_length=100)),
                ('id_flux', models.IntegerField()),
                ('order_purchase_date', models.DateField()),
            ],
        ),
    ]
