# Generated by Django 3.1.2 on 2020-11-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_purchase_date',
            field=models.DateField(null=True),
        ),
    ]
