# Generated by Django 3.1.2 on 2020-10-30 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_order_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_purchase_date',
            field=models.DateField(null=True),
        ),
    ]
